[package]
name = "tokio-dns"
version = "0.1.0"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
lazy_static = "0.2"
tokio-core = "0.1"
log = "0.3"
